### ISSUE TITLE
CaseClauseError when parsing page HTML

### ISSUE THREAD

**Issue by edevil** [rrrene/html_sanitize_ex#28]
```
iex(1)> HtmlSanitizeEx.html5(HTTPoison.get!("http://www.coolest-gadgets.com/20161026/orange-peel-pro-work/").body)
** (CaseClauseError) no case clause matching: ["//www.facebook.com/plugins/likebox.php?href=http%3A", "//www.facebook.com/plugins/likebox.php?href=http", "%3A", "", "", "", "%"]
    (html_sanitize_ex) lib/html_sanitize_ex/scrubber/html5.ex:63: HtmlSanitizeEx.Scrubber.HTML5.scrub_attribute/2
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    (html_sanitize_ex) lib/html_sanitize_ex/scrubber/html5.ex:64: HtmlSanitizeEx.Scrubber.HTML5.scrub_attributes/2
    (html_sanitize_ex) lib/html_sanitize_ex/scrubber/html5.ex:64: HtmlSanitizeEx.Scrubber.HTML5.scrub/1
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:10: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:11: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:22: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:10: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:11: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:22: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:10: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:11: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:22: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:10: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:11: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:22: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:10: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:11: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:22: HtmlSanitizeEx.Traverser.traverse/2
    (html_sanitize_ex) lib/html_sanitize_ex/traverser.ex:10: HtmlSanitizeEx.Traverser.traverse/2
```

It seems that it crashes on:

```
<iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fcoolestgadgets&amp;width=300&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;border_color=white&amp;stream=false&amp;header=true&amp;appId=131623183581267" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:300px; height:290px;" allowTransparency="true"></iframe>
```

**Comment by valpackett** [comment]
Just hit this as well :(

```elixir
iex> IO.inspect HtmlSanitizeEx.Traverser.traverse({ "img", [ {"src", "wtf%20test"} ], [] }, HtmlSanitizeEx.Scrubber.MarkdownHTML)
{"img", [{"src", "wtf%20test"}], []}

iex> IO.inspect HtmlSanitizeEx.Traverser.traverse({ "img", [ {"src", "wtf%3Atest"} ], [] }, HtmlSanitizeEx.Scrubber.MarkdownHTML)
** (CaseClauseError) no case clause matching: ["wtf%3A", "wtf", "%3A", "", "", "", "%"]
    (html_sanitize_ex) lib/html_sanitize_ex/scrubber/markdown_html.ex:41: HtmlSanitizeEx.Scrubber.MarkdownHTML.scrub_attribute/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (html_sanitize_ex) lib/html_sanitize_ex/scrubber/markdown_html.ex:42: HtmlSanitizeEx.Scrubber.MarkdownHTML.scrub_attributes/2
    (html_sanitize_ex) lib/html_sanitize_ex/scrubber/markdown_html.ex:42: HtmlSanitizeEx.Scrubber.MarkdownHTML.scrub/1
```

**Comment by rrrene** [comment]
This seems to be fixed in current. Sorry for not answering earlier :+1:
